package oop.translator;

import oop.preprocessor.*;
import oop.translator.*;
import oop.translatorTree.*;
import oop.tree.interfaces.*;

import xtc.tree.*;
import xtc.type.*;
import xtc.util.*;

import java.util.*;
import java.io.*;

public class CppAstUtil {
    public static enum NodeName {
	AdditiveExpression,
	Annotation,
	AnnotationDeclaration,
	AnnotationMethod,
	Annotations,
	Arguments,
	ArrayInitializer,
	AssertStatement,
	BasicCastExpression,
	BasicForControl,
	BitwiseAndExpression,
	BitwiseNegationExpression,
	BitwiseOrExpression,
	BitwiseXorExpression,
	Block,
	BlockDeclaration,
	BooleanLiteral,
	Bound,
	BreakStatement,
	CallExpression,
	CaseClause,
	CastExpression,
	CharacterLiteral,
	ClassBody,
	ClassDeclaration,
	ClassLiteralExpression,
	CompilationUnit,
	ConcreteDimensions,
	ConditionalExpression,
	ConditionalStatement,
	ConstructorDeclaration,
	ContinueStatement,
	Declarator,
	Declarators,
	DefaultClause,
	DefaultValue,
	Dimensions,
	DoWhileStatement,
	EmptyDeclaration,
	EmptyStatement,
	EnhancedForControl,
	EnumConstant,
	EnumConstants,
	EnumMembers,
	EqualityExpression,
	Expression,
	ExpressionList,
	ExpressionStatement,
	Extension,
	FieldDeclaration,
	FloatingPointLiteral,
	FormalParameter,
	FormalParameters,
	ForStatement,
	Implementation,
	ImportDeclaration,
	InitializationListEntry,
	InstanceOfExpression,
	InstantiatedType,
	IntegerLiteral,
	InterfaceDeclaration,
	LabeledStatement,
	LogicalAndExpression,
	LogicalNegationExpression,
	LogicalOrExpression,
	MethodDeclaration,
	Modifier,
	Modifiers,
	MultiplicativeExpression,
	NewArrayExpression,
	NewClassExpression ,
	NullLiteral,
	PackageDeclaration,
	PostfixExpression,
	PrimaryIdentifier,
	PrimitiveType,
	QualifiedIdentifier,
	RelationalExpression,
	ReturnStatement,
	SelectionExpression,
	ShiftExpression,
	SomeCatchClause,
	SomeDeclaration,
	SomeDeclarators,
	SomeExpression,
	SomeExpressionList,
	SomeImportDeclaration,
	SomeModifier,
	SomeStatement,
	StringLiteral,
	SubscriptExpression,
	SuperExpression,
	SwitchStatement,
	SynchronizedStatement,
	ThisExpression,
	ThrowsClause,
	ThrowStatement,
	TryCatchFinallyStatement,
	Type,
	TypeArguments,
	TypeInstantiation,
	TypeParameter,
	TypeParameters,
	UnaryExpression,
	VoidType,
	WhileStatement,
	Wildcard,
	WildcardBound,
    }
}